<?php

namespace AppBundle\Repository;

/**
 * ActorCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
