<?php

namespace AppBundle\Repository;

/**
 * CatalogTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
