<?php

namespace AppBundle\Repository;

/**
 * CatalogDownloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogDownloadRepository extends \Doctrine\ORM\EntityRepository
{
}
