<?php

namespace AppBundle\Repository;

/**
 * CatalogSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
