<?php

namespace AppBundle\Repository;

/**
 * CatalogSectionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogSectionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
