<?php

namespace AppBundle\Repository;

/**
 * CreatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreatorRepository extends \Doctrine\ORM\EntityRepository
{
}
