<?php

namespace AppBundle\Repository;

/**
 * CreatorCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreatorCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
