<?php

namespace AppBundle\Repository;

/**
 * DirectorCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectorCountryRepository extends \Doctrine\ORM\EntityRepository
{
	
}
