<?php

namespace AppBundle\Repository;

/**
 * MetadataTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetadataTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
