<?php

namespace AppBundle\Repository;

/**
 * MovieResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
