<?php

namespace AppBundle\Repository;

/**
 * MovieCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
