<?php

namespace AppBundle\Repository;

/**
 * MovieProducerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieProducerRepository extends \Doctrine\ORM\EntityRepository
{
}
