<?php

namespace AppBundle\Repository;

/**
 * MovieSeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieSeasonRepository extends \Doctrine\ORM\EntityRepository
{
}
