<?php

namespace AppBundle\Repository;

/**
 * MovieRewardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRewardRepository extends \Doctrine\ORM\EntityRepository
{
}
