<?php

namespace AppBundle\Repository;

/**
 * MovieLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
