<?php

namespace AppBundle\Repository;

/**
 * MovieDirectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieDirectorRepository extends \Doctrine\ORM\EntityRepository
{
}
