<?php

namespace AppBundle\Repository;

/**
 * MovieActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieActorRepository extends \Doctrine\ORM\EntityRepository
{
}
