<?php

namespace AppBundle\Repository;

/**
 * MovieCatalogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieCatalogRepository extends \Doctrine\ORM\EntityRepository
{
}
