<?php

namespace AppBundle\Repository;

/**
 * MovieTrailerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieTrailerRepository extends \Doctrine\ORM\EntityRepository
{
}
