<?php

namespace AppBundle\Repository;

/**
 * MovieCreatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieCreatorRepository extends \Doctrine\ORM\EntityRepository
{
}
