<?php

namespace AppBundle\Repository;

/**
 * MovieEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieEventRepository extends \Doctrine\ORM\EntityRepository
{
}
