<?php

namespace AppBundle\Repository;

/**
 * MovieSceneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieSceneRepository extends \Doctrine\ORM\EntityRepository
{
}
