<?php

namespace AppBundle\Repository;

/**
 * MovieEpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieEpisodeRepository extends \Doctrine\ORM\EntityRepository
{
}
