<?php

namespace AppBundle\Repository;

/**
 * OriginalLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OriginalLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
