<?php

namespace AppBundle\Repository;

/**
 * ProducerCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducerCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
