<?php

namespace AppBundle\Repository;

/**
 * WebsiteMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteMailRepository extends \Doctrine\ORM\EntityRepository
{
}
