<?php

namespace AppBundle\Repository;

/**
 * WebsiteRefererRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteRefererRepository extends \Doctrine\ORM\EntityRepository
{
}
