imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']

parameters:

    database_host: 127.0.0.1
    database_port: null
    database_name: coa_symfony
    database_user: root
    database_password: null
    mailer_transport: gmail
    mailer_host: null
    mailer_user: zakeszako@gmail.com
    mailer_password: '@@ssZ@ck284520M@bintou'

    admin:
        department: 'webmaster'
        email: 'zakeszako@yahoo.fr'
    app.site: 
        name:   'Côte Ouest Audiovisuel'
        email:  'webmaster@coteouest.ci'
        url:    'http://coteouesttv.local'
    app.vimeo:
        # mes propre acces
        # access_token: '95e6651dbfaf32ff95b86f047afa645b'
        # client_id: '7ec68730b75234b0808db6a3a1f473f1424af34e'
        # client_secret: '/lP+99w7SP7JKIxW3WydJLuzX5+AK9mkK4mkAfbRZOc9gAvGNEqlK0swUbYPBK+AeonvHddAHGmKh+5ZMnujQBPkPJOIJw6J4M/dz22LndFSt21vl1mW9zBHhkcnrkTV'

        # access cote ouest
        access_token: '8531d3e2429838d548c960e52b035148'
        client_id: '5f060d30dea49fcc03e514796218c04740792683'
        client_secret: 'GPH0T7BCY8aas5vous6KzedIXU92wwXbGKtpXfEHkr60E2fEYhRizc8eI9MGKFnRQ+/WJL55+qhhbB6+yUmx5yvnl0l+I0bFTBPw/heiXIF0NR+E5b/VjR7oB7XmdfOG'

        # access cote ouest 2
        # access_token: 'dd85a81b21555c5a34d7cd7c419aa6b4'
        # client_id: '97b9159f2231b43f90f3874ce745e2d2dda609ba'
        # client_secret: 'zfw/DV7ERqi+974In0JlP+Bnbrr6OygeWDQeYeWTwJcXvJqMfDDT3JPPLa291dy/GUHRR5T1L7gyDcOygGRkkPrp9KJ0qLYMV95nqZngouvPh9bQmRS+XnJhSitWYEv2'

        