# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        my_db_provider:
            entity:
                class: AppBundle\Entity\User
                property: email

        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: my_db_provider
            switch_user: true

            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: account_index

            logout:
                path: /security/logout
                target: /

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN,ROLE_TRANSLATOR,ROLE_CATALOG,ROLE_SALER,ROLE_OBSERVER] }
        - { path: ^/account/producer, roles: ROLE_PRODUCER }
        - { path: ^/account/actor, roles: ROLE_ACTOR }
        - { path: ^/account/director, roles: ROLE_DIRECTOR }
        - { path: ^/account, roles: IS_AUTHENTICATED_FULLY }


    role_hierarchy:
        ROLE_SUBSCRIBER: ROLE_USER
        ROLE_TRANSLATOR: ROLE_USER
        ROLE_CATALOG_UPDATE: ROLE_USER
        ROLE_CATALOG_REMOVE: ROLE_USER
        ROLE_CATALOG_INSERT: ROLE_USER
        ROLE_CATALOG: 
            - ROLE_CATALOG_UPDATE
            - ROLE_CATALOG_REMOVE
            - ROLE_CATALOG_INSERT
            - ROLE_CATALOG_GENERATE
        ROLE_SALER: ROLE_USER
        ROLE_PRODUCER: ROLE_USER
        ROLE_DIRECTOR: ROLE_USER
        ROLE_ACTOR: ROLE_USER
        ROLE_CREATOR: ROLE_USER
        ROLE_OBSERVER_CATALOG: ROLE_USER
        ROLE_OBSERVER: [ROLE_OBSERVER_CATALOG]
        ROLE_ADMIN:       [ROLE_CATALOG,ROLE_TRANSLATOR,ROLE_SALER,ROLE_OBSERVER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
