<?php
namespace AppBundle\DataFixtures;

use AppBundle\Entity\Producer;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;

class ProducerFixtures extends Fixture{

    public function load(ObjectManager $manager){

      /*  $data = ["AFRICA BROADCASTING","AKWA FILMS","ARTMATTAN PRODUCTIONS","BILIF ENTERTAINMENT PICTURE","BOSS PLAYA","C THROUGH PRODUCTION","chinneylove Eze","CLICKBOOGIE","CLICKBOOGIE MEDIA","CREATIVE UNIT STUDIO","DACHES MULTIMEDIA","DIAMOND GROOVE PICTURES","DO BOX","DO MEDIE LTD","DOPE 7 MEDIA","DV8","ECHELON STUDIO","ELJAY PRODUCTION","FAST TRACK","FILM & PICTURES","FORESIGHT BUSINESS INVESTMENT (PTY)T/A Cutting Edge Empire Entertment","GARDNER MEDIA","GOLDEN EDGE MULTIMEDIA CONSULT","Golden effects services ltd","GOLDEN EFFECTTS","GRAND SYNOPSIS MEDIA LTD","HEAVY METAL STUDIOS","HP MEDIA ENT LIMITED","IBAKA","IBAKA TV","IBAKATV","IMAGINA INTERNATIONAL","INDIGI FILM & TELEVISION LTD","INSIGNIAKENYA","Iyabo Ojo","Janitqueen Film Production Inc","JOEGA FILMS","JUDITH AUDU PROD","MAXPOT MEDIA","MELO STUDIOS","MIGHTY MAN ENTERTAINMENT","MOUNT ZION FILM PRODUCTIONS","MOUNT ZION FILM PRODUCTIONS","MOVIE M PRODUCTIONS","NATIONAL POPULATION COUNCIL","NEXT PAGE PROD","No Blondes Productions","OLD FILMS PROD","ONE JOHN 5 FOUR MEDIA","ONEJOHN 5 FOUR MEDIA","PREMIER FILM","PRINC FILMS","REALITY MOTION PICTURES","RECREATION FILMS","RIA MULTIMEDIA","ROYAL ART ACADEMY","ROYAL ROOTS","SBS","SEMBA COM","SEMBA COMMUNICACAO","SPARROW PRODUCTIONS","SPEILWORKS","STORYLAB LTD","Synergy Studios","TV3 NETWORK LTD","URBAN","URBAN HOME ENTERTAINMENT","vISIT FILMS","WILDBUNCH","YOLANDE GNÉKPIÉ BOGUI","YOUNG RICH TELEVISION LIMITED","ZODIAK",
        ];

        foreach ($data as $key => $el) {
            $e = new Producer();
            $e->setName($el);
            $manager->persist($e);
        }
        
        $manager->flush();*/
    }
}

